"""Turn a ScopingPlan into reviewable Postgres SQL.

Pure: no database connection, no side effects, deterministic output. The result is a
human-review artifact - it creates a least-privilege read-only role, grants SELECT on
only the chosen columns, and enables row-level security scoped to the session identity
on owned tables. It never emits writes, never grants secret columns, never grants EXECUTE.
"""
from __future__ import annotations

from .engines.base import ScopingPlan, TablePlan


def _q(ident: str) -> str:
    """Quote an SQL identifier."""
    return '"' + ident.replace('"', '""') + '"'


def _qualified(schema: str, name: str) -> str:
    return f"{_q(schema)}.{_q(name)}"


def _policy_name(role: str, table: str) -> str:
    return f"{role}_{table}_select"


def _header(plan: ScopingPlan) -> str:
    owned = [t for t in plan.tables if t.owner_column]
    public = [t for t in plan.tables if not t.owner_column]
    return "\n".join([
        "-- ============================================================",
        "-- HUMAN REVIEW REQUIRED - generated by support-binder",
        "-- ============================================================",
        f"-- Creates a READ-ONLY role '{plan.role}' that can SELECT only the columns",
        "-- listed below. It performs no writes and is granted no EXECUTE.",
        f"-- Row-level security scopes owned tables to the session identity: {plan.identity_expr}",
        f"--   owned (row-scoped) tables : {', '.join(t.table for t in owned) or '(none)'}",
        f"--   public (no row scoping)   : {', '.join(t.table for t in public) or '(none)'}",
        "-- Review every grant and policy before applying. Apply with a privileged",
        "-- connection; this file contains no credentials.",
        "-- ============================================================",
    ])


def _create_role(role: str) -> str:
    # Idempotent: only create if the role does not already exist.
    return "\n".join([
        "DO $$",
        "BEGIN",
        f"  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{role}') THEN",
        f"    CREATE ROLE {_q(role)} NOLOGIN;",
        "  END IF;",
        "END",
        "$$;",
    ])


def _grant_block(plan: ScopingPlan, t: TablePlan) -> str:
    cols = ", ".join(_q(c) for c in t.granted_columns)
    rel = _qualified(plan.schema, t.table)
    lines = [f"GRANT SELECT ({cols}) ON {rel} TO {_q(plan.role)};"]

    if t.kind == "view":
        lines.append(f"-- {t.table}: view - relies on underlying-table RLS / its definition; "
                     "no policy emitted.")
        return "\n".join(lines)

    if t.owner_column:
        policy = _policy_name(plan.role, t.table)
        lines += [
            f"ALTER TABLE {rel} ENABLE ROW LEVEL SECURITY;",
            # drop-then-create so re-applying the migration (e.g. after re-generating it
            # with different columns) doesn't fail on the existing policy
            f"DROP POLICY IF EXISTS {_q(policy)} ON {rel};",
            f"CREATE POLICY {_q(policy)} ON {rel}",
            f"    FOR SELECT TO {_q(plan.role)}",
            f"    USING ({plan.identity_expr} = {_q(t.owner_column)});",
        ]
    else:
        lines.append(f"-- {t.table}: public/reference table - no row scoping.")
    return "\n".join(lines)


def identity_bootstrap_sql(role: str, id_type: str) -> str:
    """SQL that creates the app.current_user_id() session-identity function the generated
    RLS policies depend on. Emitted ahead of the policies so the migration is self-contained
    (otherwise applying it fails with 'schema "app" does not exist'). The function reads a
    per-connection GUC the tool server sets from the verified session; unset => NULL => no
    rows. id_type must match the user-id column type the policies compare against."""
    return "\n".join([
        "-- Current-user function used by the row rules below. Your app sets this value on",
        "-- each connection; if it isn't set, the role sees no rows. Change the ::%s cast"
        % id_type,
        "-- if your user id column is a different type.",
        "--     SET app.current_user_id = '<current-user-id>';",
        "CREATE SCHEMA IF NOT EXISTS app;",
        f"CREATE OR REPLACE FUNCTION app.current_user_id() RETURNS {id_type}",
        "    LANGUAGE sql STABLE",
        f"    AS $$ SELECT NULLIF(current_setting('app.current_user_id', true), '')::{id_type} $$;",
        f"GRANT USAGE ON SCHEMA app TO {_q(role)};",
        f"GRANT EXECUTE ON FUNCTION app.current_user_id() TO {_q(role)};",
    ])


def build_sql(plan: ScopingPlan) -> str:
    """Render the full migration SQL for a ScopingPlan."""
    parts: list[str] = [_header(plan), ""]
    parts.append(_create_role(plan.role))
    parts.append("")
    parts.append(f"GRANT USAGE ON SCHEMA {_q(plan.schema)} TO {_q(plan.role)};")
    parts.append("")
    # Identity-function bootstrap, if any, must precede the policies that reference it.
    if plan.identity_setup_sql:
        parts.append(plan.identity_setup_sql)
        parts.append("")
    for t in plan.tables:
        parts.append(_grant_block(plan, t))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"
